### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by chimaerra** [maggot99999/source-live-audio-mixer#3]
@maggot99999 , you're a legend, I've spent 6 hours trying to fix older(1.5.4) version of SLAM, trying to implement different libs like youtubeexplode or libvideo that you used, but because I'm silly in programming overall and more than that in Visual Basic(it's somewhat a zone of my zero knowledge) I wasn't been able to do that. Since SLAM's original author doesn't make any uploads since 2017, it would be great to at least let people know that there are fixed version of the program they're trying to use. SLAM's reddit, issues page just as YoutubeExtractor issues page have many requests to help them with code while this version already has some great additional abilities. If you don't have time to support this project further(and that would be really stupid to ask to do so) - please, at least post latest working version on SLAM's issues page & reddit. If that's unacceptable - just say so. And yeah, post a link to your patreon or something, there should be grateful people. Thanks again.

**Comment by Hackmastr** [comment]
Hello @chimaerra,

Indeed, Maggot did a lot of work!
However, as you said, it is impossible to post/pin a post announcing a new version, I tried to contact Silent, but he didn't seem interested in making any changes.

Here is the Reddit link: https://www.reddit.com/r/SourceLiveAudioMixer/
Here is an updated version, including Maggots updates: https://www.reddit.com/r/SourceLiveAudioMixer/comments/bbczf5/version_161_youtube_fixed/

~~However, I think this version doens't work either, since YouTube made some changes. If I have sometime this noon I'll push a new update (to this repo).~~

Edit: I tested it now and it worked.

**Comment by Hackmastr** [comment]
Drafted a new version
https://github.com/maggot99999/source-live-audio-mixer/releases/tag/v1.6.1

**Comment by chimaerra** [comment]
> However, as you said, it is impossible to post/pin a post announcing a new version, I tried to contact Silent, but he didn't seem interested to make any changes.

That's kinda "bad" to know. I thought that he just abandoned his project due to a lack of motivation as it's not a rare thing to happen. 

There's something wrong with the libvideo or something, sometimes it doesn't want to import videos from YouTube, at first I thought that it happens only with videos that have special characters or arabic or cyrillic but thing is that it happens sort of randomly(?). 
Error log: 
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at VideoLibrary.YouTubeVideo.Decryptor.ExecuteFunction(String signature, String line, String function)
   at VideoLibrary.YouTubeVideo.DecryptSignature(String js, String signature)
   at VideoLibrary.YouTubeVideo.<DecryptAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.YouTubeVideo.<GetUriAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.VideoClient.<GetBytesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в VideoLibrary.Video.<GetBytesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VideoLibrary.Video.GetBytes()
   at SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e) в G:\Projects\source-live-audio-mixer\SLAM\YTImport.vb: 51
```

for example: it happens with https://www.youtube.com/watch?v=E5ONTXHS2mM and with https://www.youtube.com/watch?v=QUBvVTNRp4Q too. Idk what's wrong with these but there are many of them that gonna lead to this error.

**Comment by chimaerra** [comment]
Nevermind, it works perfectly with this stable fork of libvideo: https://github.com/omansak/libvideo 
there was an issue with latest version of libvideo's original branch https://github.com/i3arnon/libvideo/issues/139

**Comment by Hackmastr** [comment]
Cheers @chimaerra!
I'll update it this afternoon.

**Comment by Hackmastr** [comment]
Drafted new version with updated libvideo.

Thanks @chimaerra!
